export const SYS_MSG = {
  SUCCESS: 'Request completed successfully',
  RETRIEVED: 'Resource retrieved successfully',
  CREATED: 'Resource created successfully',
  UPDATED: 'Resource updated successfully',
  DELETED: 'Resource deleted successfully',
  ACCEPTED: 'Request accepted for asynchronous processing',
  NO_CONTENT: 'Request completed successfully with no response body',
  BAD_REQUEST: 'The request could not be processed because it is invalid',
  UNAUTHORIZED: 'Authentication is required or has failed',
  FORBIDDEN: 'You do not have permission to access this resource',
  NOT_FOUND: 'The requested resource was not found',
  CONFLICT: 'The request conflicts with the current resource state',
  VALIDATION_FAILED: 'Request validation failed',
  INTERNAL_SERVER_ERROR: 'An unexpected server error occurred',
  INVALID_CREDENTIALS: 'The provided email or password is incorrect',
  INVALID_REFRESH_TOKEN:
    'The refresh token is invalid, expired, or cannot be used',
  INVALID_OTP: 'The verification code is invalid or has expired',
  OTP_ATTEMPTS_EXCEEDED: 'Too many verification attempts. Try again later',
  EMAIL_NOT_VERIFIED: 'This user email is not verified',
  OTP_NOT_EXPIRED: 'Your otp has not expired yet',
} as const;
